name: senselogic_gson
description: Granular Structured Object Notation.
homepage: https://github.com/senselogic/GSON
repository: https://github.com/senselogic/GSON
version: 0.1.6

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  crypto: ^3.0.6
